# Dockerfile_youtube_client
FROM python:3.9-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos necessários para o contêiner
COPY main.py /app/main.py
COPY VPN_SERVER/ /app/VPN_SERVER/
COPY videos_to_watch.json /app/videos_to_watch.json
COPY requirements.txt /app/requirements.txt

# Instala as dependências necessárias
RUN pip install --no-cache-dir -r /app/requirements.txt

# Comando para iniciar o cliente do YouTube
CMD ["python", "/app/main.py"]
